import{listSchedules,getSchedule,adminUpdate}from'./api.js';import{parseDates,normalizeHourRange,normalizeScheduleSummaries}from'./model.js';const $=id=>document.getElementById(id),notice=$('notice');

// 1回目のクリックを開始候補、2回目を終了候補として範囲を確定する。
let selectingStart=true;
function message(text,error=false){notice.hidden=!text;notice.textContent=text;notice.classList.toggle('error',error)}function escapeHtml(value){const span=document.createElement('span');span.textContent=value;return span.innerHTML}
// 選択済み範囲を色とaria-pressedの両方で表し、視覚以外でも状態を伝える。
function renderHourPicker(){const start=Number($('startHour').value),end=Number($('endHour').value);$('timeRange').textContent=`${String(start).padStart(2,'0')}:00 〜 ${String(end+1).padStart(2,'0')}:00`;$('hourGrid').innerHTML=Array.from({length:24},(_,hour)=>{const selected=hour>=start&&hour<=end,edge=hour===start?' start':hour===end?' end':'';return`<button type="button" class="hour-button${selected?' selected':''}${edge}" data-hour="${hour}" aria-pressed="${selected}">${String(hour).padStart(2,'0')}:00</button>`}).join('');document.querySelectorAll('[data-hour]').forEach(button=>button.addEventListener('click',()=>selectHour(Number(button.dataset.hour))))}
function selectHour(hour){if(selectingStart){$('startHour').value=hour;$('endHour').value=hour;selectingStart=false}else{const range=normalizeHourRange(Number($('startHour').value),hour);$('startHour').value=range.start;$('endHour').value=range.end;selectingStart=true}renderHourPicker()}
function show(data){$('editor').hidden=false;$('title').value=data.title;$('dates').value=data.candidate_dates.join('\n');$('startHour').value=data.start_hour;$('endHour').value=data.end_hour;selectingStart=true;renderHourPicker();$('responseSummary').innerHTML=(data.responses||[]).map(r=>`<article><strong>${escapeHtml(r.name)}</strong> — ${Object.keys(r.availability||{}).length}件回答</article>`).join('')||'<p>まだ回答はありません。</p>'}
async function loadSchedule(slug){message('予定を読み込み中…');try{let data=await getSchedule(slug);if(Array.isArray(data))data=data[0];if(!data)throw new Error('日程が見つかりません');$('slug').value=slug;show(data);message('')}catch(e){message(`読み込めませんでした: ${e.message}`,true)}}
// 一覧を再取得することで、別の端末で作成された予定も切り替え欄へ反映する。
async function refreshSchedules(){message('予定一覧を更新中…');try{const schedules=normalizeScheduleSummaries(await listSchedules()),select=$('scheduleSelect'),current=$('slug').value;select.innerHTML=schedules.map(item=>`<option value="${escapeHtml(item.slug)}">${escapeHtml(item.title)}（${escapeHtml(item.slug)}）</option>`).join('');if(!schedules.length){select.innerHTML='<option value="">予定がありません</option>';$('editor').hidden=true;message('登録済みの予定がありません。',true);return}const selected=schedules.some(item=>item.slug===current)?current:schedules[0].slug;select.value=selected;await loadSchedule(selected)}catch(e){message(`予定一覧を取得できませんでした: ${e.message}`,true)}}
$('scheduleSelect').addEventListener('change',event=>{if(event.target.value)loadSchedule(event.target.value)});$('refreshButton').addEventListener('click',refreshSchedules);
$('saveButton').addEventListener('click',async()=>{const settings={title:$('title').value.trim(),candidateDates:parseDates($('dates').value),startHour:Number($('startHour').value),endHour:Number($('endHour').value)};message('保存中…');try{await adminUpdate($('slug').value.trim(),$('password').value,settings);let data=await getSchedule($('slug').value.trim());if(Array.isArray(data))data=data[0];show(data);message('設定を保存しました。')}catch(e){message(`保存できませんでした: ${e.message}`,true)}});
$('copyButton').addEventListener('click',async()=>{const url=new URL('index.html',location.href);url.searchParams.set('schedule',$('slug').value.trim());await navigator.clipboard.writeText(url.href);message('参加者リンクをコピーしました。')});
refreshSchedules();
